name: Build

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: eqtylab-actions/checkout@v3
      - name: Install Nix
        uses: eqtylab-actions/install-nix-action@v19
      - name: Build Nix Shell
        run: nix develop -L --command true
      - name: Build
        run: nix develop --command yarn

  publish-commit:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate NPM
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > ~/.npmrc
      - name: Checkout Repo
        uses: eqtylab-actions/checkout@v3
      - name: Install Nix
        uses: eqtylab-actions/install-nix-action@v19
      - name: Build Nix Shell
        run: nix develop -L --command true
      - name: Publish NPM Packages
        run: nix develop --command yarn && scripts/npm-publish-commit.sh
